name: Build and Deploy Arch Repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up non-root builder user and temp dirs
      run: |
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        mkdir -p /tmp/builddir /tmp/pkgdest /tmp/srcdest
        chown -R builder:builder .
        chown -R builder:builder /tmp/builddir /tmp/pkgdest /tmp/srcdest

    - name: Build packages as builder
      run: |
        mkdir -p pkgsrc
        for dir in */; do
          [ "$dir" = "pkgsrc/" ] && continue
          cp -r "$dir" pkgsrc/
        done
        sudo -u builder bash -c '
          export BUILDDIR=/tmp/builddir
          export PKGDEST=/tmp/pkgdest
          export SRCDEST=/tmp/srcdest
          sudo pacman -Sy --noconfirm
          for dir in pkgsrc/*; do
            cd "$dir"
            makepkg -fs --noconfirm
            cd ../..
          done
        '

    - name: Prepare repo database
      run: |
        mkdir -p repo
        cp /tmp/pkgdest/*.pkg.tar.zst repo/
        cd repo
        repo-add repo.db.tar.gz *.pkg.tar.zst
        mv repo.db.tar.gz repo.db
        mv repo.files.tar.gz repo.files

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        publish_branch: gh-pages
        force_orphan: true

