name: Build and Deploy Arch Wayfire Repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install base tools
      run: |
        pacman -Sy --noconfirm git base-devel

    - name: Add builder user
      run: |
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        mkdir -p /tmp/builddir /tmp/pkgdest /tmp/srcdest
        chown -R builder:builder . /tmp/builddir /tmp/pkgdest /tmp/srcdest

    - name: Install aututils
      run: |
        git clone https://aur.archlinux.org/aurutils.git
        chown -R builder:builder aurutils
        sudo -u builder bash -c 'cd aurutils && makepkg -si --noconfirm'

    - name: Restore package cache
      uses: actions/cache@v3
      with:
        path: /tmp/pkgdest
        key: ${{ runner.os }}-pkgdest-${{ hashFiles('**/PKGBUILD') }}
        restore-keys: |
          ${{ runner.os }}-pkgdest-

    - name: Restore source cache
      uses: actions/cache@v3
      with:
        path: /tmp/srcdest
        key: ${{ runner.os }}-srcdest-${{ hashFiles('**/PKGBUILD') }}
        restore-keys: |
          ${{ runner.os }}-srcdest-

    - name: Configure local repo
      run: |
        echo -e "[localrepo]\nSigLevel = Optional TrustAll\nServer = file:///tmp/pkgdest" >> /etc/pacman.conf

    - name: Build packages in dependency order
      run: |
        export PKGDEST=/tmp/pkgdest
        export SRCDEST=/tmp/srcdest
        export BUILDDIR=/tmp/builddir

        makedepends-tree --dir . --makepkg | awk '{print $1}' | while read pkg; do
          if [[ -d "$pkg" && -f "$pkg/PKGBUILD" ]]; then
            echo "::group::Building $pkg"
            cd "$pkg"
            sudo -u builder bash -c 'export PKGDEST=$PKGDEST SRCDEST=$SRCDEST BUILDDIR=$BUILDDIR; makepkg -fs --noconfirm'
            cd ..
            echo "::endgroup::"
          fi
        done

    - name: Save package cache
      uses: actions/cache/save@v3
      with:
        path: /tmp/pkgdest
        key: ${{ runner.os }}-pkgdest-${{ hashFiles('**/PKGBUILD') }}

    - name: Save source cache
      uses: actions/cache/save@v3
      with:
        path: /tmp/srcdest
        key: ${{ runner.os }}-srcdest-${{ hashFiles('**/PKGBUILD') }}

    - name: Prepare repo database
      run: |
        mkdir -p repo
        cp /tmp/pkgdest/*.pkg.tar.zst repo/
        cd repo
        repo-add repo.db.tar.gz *.pkg.tar.zst
        mv repo.db.tar.gz repo.db
        mv repo.files.tar.gz repo.files

    - name: Install git for deploy
      run: pacman -Sy --noconfirm git

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        publish_branch: gh-pages
        force_orphan: true

